name: .NET

env:
 registry: ka123devopsreg.azurecr.io
 repository: wth/dotnetcoreapp
 docker_path: Application/src/RazorPagesTestSample/
 webapp_name: ka123devops-dev

on:
  push:
    paths:
       - 'Application/*'
    branches: [ main ]
  #pull_request:
    #branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      #with:
        #dotnet-version: 2.2
    - name: Restore dependencies
      run: dotnet restore Application/src/RazorPagesTestSample/*.csproj
    - name: Build
      run: dotnet build --configuration Release --no-restore Application/src/RazorPagesTestSample/*.csproj
    - name: Test
      run: dotnet test --no-build --verbosity normal  Application/tests/*
      
   
  ####################### The following is needed for Challenge#5 #############
  docker_build_and_push:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build_and_test
    steps: 
    - uses: actions/checkout@v2
    - name: Docker login
      run: docker login $registry -u ${{ secrets.ACR_USERNAME }} -p ${{ secrets.ACR_PASSWORD }}
       
    - name: Docker build
      run: docker build -t $registry/$repository:${{github.run_number}} --build-arg build_version=${{github.run_number}} $docker_path
  
    - name: Docker Push
      run: docker push $registry/$repository:${{github.run_number}}
    - uses: actions/github-script@0.9.0
      if: failure()
      with:
        github-token: ${{secrets.GITHUBTOKEN}}
        script: |
          let body = "${{ env.build_name }} Worflow Failure \n Build Number: ${{ github.run_number }} \n Build Log: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} \n SHA: [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }}) \n";
          github.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: "${{ env.build_name }} Workflow ${{ github.run_number }} Failed! ",
            body: body
          });

####################### The following is needed for Challenge#6 #############
### The following code Deploys to Staging Slot. #####
  deploy_to_staging_slot:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: docker_build_and_push
    steps:
    - name: Azure Login
      uses: Azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure WebApp staging slot
      uses: Azure/webapps-deploy@v2
      with:
        app-name: ${{ env.webapp_name }} 
        #slot-name: staging
        #images: openhackggp0ljh0acr.azurecr.io/devopsoh/api-poi:${{ github.run_number }} 
        images: ${{ env.registry }}/${{ env.repository }}:${{ github.run_number }}   
 
    - name: Azure Logout
      run: az logout
      
    - uses: actions/github-script@0.9.0
      if: failure()
      with:
        github-token: ${{secrets.GITHUBTOKEN}}
        script: |
          let body = "${{ env.build_name }} Worflow Failure \n Build Number: ${{ github.run_number }} \n Build Log: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} \n SHA: [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }}) \n";
          github.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: "${{ env.build_name }} Workflow ${{ github.run_number }} Failed! ",
            body: body
          });
