name: .NET

env:
 #ACR_USERNAME: ka123devopsreg
 #ACR_PASSWORD: BDGBwl8tw0dV56oNK28/7hIu3k13nvpl
 #ACR_LOGIN_SERVER: ka123devopsreg.azurecr.io
 registryName: ka123devopsreg
 repositoryName: wth/dotnetcoreapp
 dockerFolderPath: Application/src/RazorPagesTestSample/
 #tag: github.run_number
 
on:
  push:
    paths:
       - 'Application/*'
    branches: [ main ]
  #pull_request:
    #branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      #with:
        #dotnet-version: 2.2
    - name: Restore dependencies
      run: dotnet restore Application/src/RazorPagesTestSample/*.csproj
    - name: Build
      run: dotnet build --configuration Release --no-restore Application/src/RazorPagesTestSample/*.csproj
    - name: Test
      run: dotnet test --no-build --verbosity normal  Application/tests/*
      
### The following code builds the docker image and pushes it to ACR #####
  docker_build_and_push:
    #if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:     
    - uses: actions/checkout@v2
    - name: Docker login
      uses: Azure/docker-login@v1     
      with:
        #ACR URL
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        #ACR name
        username: ${{ secrets.ACR_USERNAME }}
        #ACR password
        password: ${{ secrets.ACR_PASSWORD }}
        #run: docker login ${{secrets.ACR_LOGIN_SERVER}} -u ${{secrets.ACR_USERNAME}} -p ${{secrets.ACR_PASSWORD}}
        #run: docker login $registry -u ${{secrets.ACR_USERNAME}} -p ${{secrets.ACR_PASSWORD}}

    - name: Docker build
      run: docker build -t $registryName/$repositoryName:${{github.run_number}} --build-arg build_version=${{github.run_number}} $dockerFolderPath

    - name: Docker Push
      run: docker push $registryName/$repositoryName:${{github.run_number}}  
      
